'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Partial Public Class Clientes
    Protected WithEvents txtNuevoNombre As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNuevoCorreo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNuevoTelefono As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents gvClientes As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
End Class
