'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Partial Public Class Site
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
