'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Partial Public Class AgendarCita
    Protected WithEvents ddlClientes As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlProcedimientos As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtFechaCita As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnConfirmar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
End Class
