'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Partial Public Class Login
    Protected WithEvents txtCorreo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtContrasena As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
End Class
