'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Partial Public Class VerCitas
    Protected WithEvents gvCitas As Global.System.Web.UI.WebControls.GridView
End Class
